# Generated by Django 4.2.5 on 2023-09-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_datetime_notification', models.DateTimeField(verbose_name='Время исполнения задачи')),
                ('message_text', models.CharField(max_length=255, verbose_name='Текст Задачи')),
                ('message_type', models.IntegerField(choices=[(1, 'Работа'), (2, 'Спорт'), (3, 'Учеба')], default=1, verbose_name='Тип Задачи')),
                ('message_status', models.BooleanField(choices=[(True, 'Сделано'), (False, 'He cделано')], default=False, verbose_name='Статус Записи')),
            ],
        ),
    ]
