# Generated by Django 4.2.5 on 2023-10-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_rename_message_datetime_notification_messagemodel_datetime_notification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='type',
            new_name='types',
        ),
    ]
