# Generated by Django 4.2.5 on 2023-10-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_rename_type_messagemodel_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'ordering': ['-datetime_notification']},
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
