# Generated by Django 4.2.5 on 2023-12-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_alter_messagemodel_options_messagemodel_important'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'ordering': ['is_done', '-expiring', '-important', 'datetime_notification']},
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='expiring',
            field=models.BooleanField(default=False),
        ),
    ]
