# Generated by Django 4.2.5 on 2024-02-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_messagemodel_options_messagemodel_expiring'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'ordering': ['-important', 'is_done', '-expiring', 'datetime_notification']},
        ),
    ]
